Taylor Diagram test
NCAR/geocat-viz pull request #234
Opened 2024-05-01 18:14 UTC by jukent

Not super sleek, this is a slightly smaller version of our example.

Going to rename the function and add each part of the taylor class as a separate test.

2024-05-03 21:02 UTC, kafitzgerald reviewed
Nice!  

Any additional thoughts on the [image](https://pytest-mpl.readthedocs.io/en/stable/image_mode.html) vs [hash](https://pytest-mpl.readthedocs.io/en/stable/hash_mode.html) comparison options?  Seems like we probably need to make a call here soon so that we can get these running in CI.  

It looks like we might want to consider setting some additional config options like deterministic metadata and the style to "default."  [See here](https://pytest-mpl.readthedocs.io/en/stable/configuration.html
).

Some additional thoughts inline as well.

2024-05-13 01:57 UTC, kafitzgerald requested changes
I'm seeing some failures on this locally from text and graphical diffs (see the example below), but only when I run with `pytest --mpl` to run the image tests.  I think we may need to update CI to run these that way or the image tests may not really run (though it appears as if they do).  

Not totally sure what to do about the failures.  I'm a little surprised there's still so much text in the figures.  We could look into that, version pins, and/or adjusting the tolerance.

I'm also wondering if we should move the baseline directory into tests?  It might be a little cleaner from an organizational perspective and then we don't need to remove another directory from that packaged versions.  If I recall correctly, this docs suggested doing something like this (i.e. moving the baseline directory and images somewhere under the test directory after checking them).

I can dig into some of this a bit more this week if that's helpful.  

![result-failed-diff](https://github.com/NCAR/geocat-viz/assets/7872563/a0584ba9-8547-4768-b968-89c4251e717c)
Here's the info from my test session:
```
platform darwin -- Python 3.12.3, pytest-8.1.1, pluggy-1.4.0
Matplotlib: 3.8.4
Freetype: 2.12.1
rootdir: /Users/katelynw/test_ing/geocat-viz
configfile: setup.cfg
plugins: cov-5.0.0, mpl-0.17.0
collected 7 items 
```

2024-05-15 20:53 UTC, jukent commented
@kafitzgerald I deleted my environment and built the images again with a clean environment within the tests/ folder as we discussed. Could you check again if you still have local image diffs (also trying with a fresh environment)?

2024-06-06 18:50 UTC, kafitzgerald approved these changes

2024-06-06 18:50 UTC, merged